### ISSUE TITLE
Sant’Anna and Zhao weights are different

### ISSUE THREAD

**Issue by pedrohcgs** [Mixtape-Sessions/Causal-Inference-2#2]
Just want to mention that the weights mentioned here are not equivalent to thosenin Sant’Anna and Zhao’s (2020) .

SZ use Hayek-type weights while those here are Horwitz-Thompson ones. SZ weights are guaranteed to sum up to one in finite samples, while those here are not.

This matters for stability when overlap is not perfect.

**Comment by kylebutts** [comment]
Thanks Pedro. Let me make sure I understand this correctly. I was going off of this estimator: https://github.com/pedrohcgs/DRDID/blob/master/R/drdid_panel.R. Is this not the Horwitz-Thompson weights?

**Comment by kylebutts** [comment]
Ahhhhh, ok I think I follow @pedrohcgs. I was basing off of `ipw_did_panel` which I believe uses Horwitz-Thompson weights. You are recommending `std_ipw_did_panel` with the main change being:
https://github.com/pedrohcgs/DRDID/blob/8a1c09f932b142e6c3b8281cd3177ab302c583d2/R/std_ipw_did_panel.R#L103
https://github.com/pedrohcgs/DRDID/blob/8a1c09f932b142e6c3b8281cd3177ab302c583d2/R/ipw_did_panel.R#L11

**Comment by pedrohcgs** [comment]
Yes.
Abadie used the H-T type pscores weights, though.

SZ is all about Hayek weights

----------------------------------------------------
*Pedro H. C. Sant'Anna*
*https://psantanna.com <https://psantanna.com>*

----------------------------------------------------
Warning: This email may contain confidential or privileged information
intended only for the use of the individual or entity to whom it is
addressed. If you are not the intended recipient, please understand
that any disclosure, copying, distribution, or use of the contents
of this email is strictly prohibited.
----------------------------------------------------
